name: Upload Python Package

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        MATURIN_USERNAME: ${{ secrets.PYPI_USERNAME }}
        MATURIN_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        docker --rm -v "$PWD:/io" run docker.pkg.github.com/colin-daniels/maturin-docker/maturin:0.8.3-1.48.0 \
          publish                        \
          --bindings=pyo3                \
          --manylinux=2010               \
          --username=${MATURIN_USERNAME} \
          --password=${MATURIN_PASSWORD} \
          --repository-url https://test.pypi.org/legacy/
